### ISSUE TITLE
mot de passe config version 4?

### ISSUE THREAD

**Issue by skydnot** [JpEncausse/SARAH-Documentation#12]
Bonjour, J'ai commencer avec la version 3 mais ayant essayer beaucoup de plugin qui ne fonctionnait pas....
je me suis dit que sur la 4 ca pourrais être différent. Alors je sais demander l'heure a sarah, chouette, mais quand je veux acceder a la config de sarah il me demande un nom d'utilisateur et un mot de passe.....
que je ne connait pas....
<img width="939" alt="capturesarah" src="https://cloud.githubusercontent.com/assets/23465757/20288911/f30c91fa-aad6-11e6-88e1-3278ce4441f4.PNG">

**Comment by JpEncausse** [comment]
Bonjour, la réponse a été posté sur la communauté G+ le login/pass est admin/password définit dans les propriétés

**Comment by Aymkdn** [comment]
Et je l'ai ajouté dans la doc : http://jpencausse.github.io/SARAH-Documentation/?page=getting_started_v4#d-marrer
