### ISSUE TITLE
node.exe non compatible avec Win10

### ISSUE THREAD

**Issue by kunux** [JpEncausse/SARAH-Documentation#13]
bonjour,
J'ai installé un Win10 tout neuf pour tester SARAH.
Malheureusement il y a une incompatibilité apparement, au lancement du serveur:

`This` version of "chemin de SARAH"/node.exe is not compatible with this version of windows you're running.``

**Comment by Aymkdn** [comment]
On est nombreux à utiliser Windows 10, et ça fonctionne !

Lis bien la doc pour être sur que tu suis bien toutes les étapes peut-être.
