### ISSUE TITLE
client Microphone.cmd missing  and Start_client.cmd not functionning

### ISSUE THREAD

**Issue by Fabvax** [JpEncausse/SARAH-Documentation#14]
hi, i did download the version 4.0 of SARAH, did all the installation regarding to the site and i realised that the file client microphone.cmd is missing, and that Start_Client.cmd is giving me this message :;
Windows can't find "C:\Program". verify you entered the right name than retry"...
Can anybody help me on that?
![2018-01-15_16h05_31](https://user-images.githubusercontent.com/35459414/34948700-330caff6-fa0e-11e7-8c1f-0fd79414ccde.png)

**Comment by Aymkdn** [comment]
Please don't use spaces into the pathname. Move your Jarvis folder somewhere else (here the problem is due to the "Program Files" with a space between "Program" and "Files")

**Comment by Fabvax** [comment]
Merci,

Vous parlez français je présume. J'ai un autre soucis, le lancement continue une fois le client lancé et il me lance le message ''impossible de détecter la version de SARAH''

Je n'ai pas non plus le fichier client microphone. que puis-je faire?

**Comment by Aymkdn** [comment]
Perso je n'utilise plus Sarah (je suis passé sur Google Home avec [asssitant-plugins](https://aymkdn.github.io/assistant-plugins/)).

Je pense que personne ne verra ton message ici (sauf moi car j'avais gardé les notifications actives ^^), donc je te conseillerais de poser ta question sur la communauté plutôt : https://plus.google.com/u/0/communities/105964514508504667709

**Comment by Fabvax** [comment]
(vide)
