### ISSUE TITLE
Amélioration autour du emulate

### ISSUE THREAD

**Issue by Tibus** [JpEncausse/SARAH-Documentation#5]
Le ?emulate et le ?tts du client sont très pratique quand la reconnaissance ce fait autrepart que sur le client lui même... par exemple, dans les applications Android et IOS gérant Sarah. Cependant, quelques ajouts et debug serai très utiles pour que ces applications puissent aller encore plus loin :
 
- Pouvoir faire un émulate sans vocalisation de la réponse. En ajoutant &notts par exemple dans l'url, le client renverrai la réponse de Sarah, ferai les action associés au plugin mais ne parlerai pas... (pour pouvoir faire le tts sur l'appliaction mobile ou sur un client custom hors Sarah)
- Quand le client ne comprends pas l'émulate, retourner quelques chose de spécial pour savoir qu'il n'a pas compris. Pour l'instant, quand un emulate n'est pas reconnu, le retour contient la dernière réponse dites par le client (parfois une liste de toutes les dernière réponses aussi). Il serai donc intéressant de faire une phrase spécial ou une suite de caractère spécial qui pourrai être reconnu par une application externe comme une réponse de non compréhension.

**Comment by Aymkdn** [comment]
Je ferme ce vieux ticket et je copie @JpEncausse dessus s'il veut réagir !
