### ISSUE TITLE
Problem with client and multiple networks

### ISSUE THREAD

**Issue by SeraphicRav** [JpEncausse/SARAH-Documentation#6]
Hi !

I have 2 network cards on a virtual machine hosting Sarah client. This machine is on 2 different networks, say 192.168.0.* and 192.168.1.*. When trying Sarah controller from a device on the 192.168.0.*, I get nothing in my logs.

When I look, on the client logs, I can see that a server is launched for 127.0.0.1 and for the network 192.168.1.* so I am missing one.

Can you do something :)

Best regards !

**Comment by Aymkdn** [comment]
(sorry for the delay, I didn't know there were issues posted here ^^)

It's a known bug. I think @JpEncausse  changed that with SARAH v4 allowing the users to select the interface they want to use for the client.

(I'm closing the issue in the meantime)
