### ISSUE TITLE
Liste des plugins

### ISSUE THREAD

**Issue by AymericDef** [JpEncausse/SARAH-Documentation#8]
Bonjour,
La liste des plugins a télécharger ne s'affiche pas.
http://img15.hostingpics.net/pics/563161errorSARAH.png

Quand je lance Start_Client.cmd il m'affiche un message
http://img15.hostingpics.net/pics/230773error.png
Alors que la version 3.1.5 fonctionne correctement

J'ai w7 professionnel
AymericDef

**Comment by JpEncausse** [comment]
La liste des plugins ne s'affichent pas sur le serveur car le marketplace chez Gandi est tombé et j'attends un retour de leur part (il y a un post sur G+ a ce sujet)

L'erreur affiché explique un problème lié au SpeechRecognitionEngine qui semble mal installé vérifie que tu as installé tous les pré-requis (qui sont dans la doc et le README et G+)
- SDK SAPI 11 + la langue
- SDK Kinect 2 + la langue
