### ISSUE TITLE
Des débuts difficiles ...

### ISSUE THREAD

**Issue by Duplodocus** [JpEncausse/SARAH-Documentation#9]
Salut,

Ca fait une bonne semaine que j'ai commencé l'expérience Sarah en utilisant la dernière release de la v4. La reconnaissance et la synthèse vocale tournent bien, le plugin time fonctionne aussi. Par contre ça s'arrête là ...
J'ai passé quelques soirées à fouiller sur le net et sur la doc Sarah sans trouver de réponses.
Voici les soucis rencontrés :

Meteo :
Lorsque je l'ai installé il était configuré de base sur Versaille, j'ai changé  le code postal par 35000 pour Rennes. Il n'a jamais indiqué Rennes mais "undefined", j'ai essayé de remettre le code postal de Versaille, même résultat.
Lorsque je lui demande la météo elle me dit "l'action a échouée" (si je me rappel bien).

Minuterie :
Prend bien en compte la demande de minuterie mais à la fin du décompte, j'ai un retour sur le serveur (une URL que je n'ai pas copier/coller) sans aucun retour vocal.

Freebox :
C'est le plugin que je souhaite principalement utiliser. Lorsque je lui demande d'allumer la freeboite elle me dit "L'action a echouée" et le serveur me retourne :
url=http://hd1.freebox.fr/pub/remote_control?code=1234&key=power
info: call(freebox) in  50ms

Lorsque je lance la commande via firefox ça ne fonctionne pas non plus pourtant je suis sur du code, je l'ai changé et testé :
Forbidden
You don't have permission to access this file on this server.
Cheyenne/2.2.8 Server at localhost Port 80

J'ai bien essayé de remplacer par hd2 mais là j'ai un timeout, donc c'est bien hd1, j'ai aussi testé avec l'adresse IP.

Pour conclure j'ai bien tenté pas mal de chose et regadé la doc mais rien n'y fait... Un petit coup de pouce serait le bien venu.
En écrivant ce message je me rend compte que dans la liste des plugins il y a des plugin V3, V4 et all. Ne serait ce pas un souci de compatibilité? Pourtant j'installe les plugins via l'interface web de la v4 ou tous les plugins sont présents.

Merci

DuplO

**Comment by JpEncausse** [comment]
SARAH n'est pas un produit mais un frawmework, il faut donc comprendre et bidouiller les plugins en échangeant sur le forum et la communauté. 

GitHub ne gere que les problème coeur. A noter que certain plugin doivent etre ajusté pour marcher avec la v4

Meteo : Ce sujet est échangé sur la communauté SARAH. Le plugin interroge un site météo en lui envoyant les paramètre qu'il attends. Il faut donc aller voir sur le site les codes de ville. Ce ne sont pas des code postaux (je ne sais pas pourquoi)

Pour Renne c'est http://www.meteo-france.mobi/ws/getDetail/france/352380.json

Minuterie : Il faut contacter le développeur du plugin sur la communauté qui aura certainement une explication

Freebox :  Il faut contacter le développeur du plugin, de ce que j'ai lu sur la communauté il faut indiquer le code Freebox

Bref demander aux développeurs de plugin, et regarder les JS pour comprendre ce que fait le plugin. On sait jamais il pourrait y avoir un plugin qui format le disque dur ;-)

**Comment by Duplodocus** [comment]
Bonjour JP,

Merci pour la réponse aussi rapide, j'ai regardé ta présentation d'une heure sur Sarah les docs et autres, je comprends donc bien le scope et le fait que ce soit pour les bidouilleurs. C'est pourquoi j'ai passé une semaine à fouinner par moi même avant de demander un coup de main. Je ne suis pas expert en dev, c'est ausi pour moi une manière de m'y mettre.

J'ai posté sur GitHub car j'ai vu le lien "Issues" sur la communoté Google. Je ne voulai pas faire un post trop long sur Google +.
Je suis donc rassuré maintenant que le souci ne vienne pas de la compatibilité de plugin mais de cout de tournevis à donner sur chaque plugin.

Merci pour ton travail colossal et ton support.

A+

DuplO
